### ISSUE TITLE
Detect powered on

### ISSUE THREAD

**Issue by terryhendrix** [WeeJeWel/net.weejewel.xboxone#1]
is it possible to detect that the i've just powered on the xbox one? I'd like to change the lights then. :)

**Comment by dvanp** [comment]
I'd really like this as well, but it seems this app isn't getting a lot of love lately.. :-(

**Comment by WeeJeWel** [comment]
This project will be maintained here: https://github.com/rkokkelk/net.weejewel.xboxone
