### ISSUE TITLE
Changed to repo to new location

### ISSUE THREAD

**Issue by rkokkelk** [WeeJeWel/net.weejewel.xboxone#3]
Hi, 

Just for references, I've moved the new Xbox repo to a new location [here](https://github.com/rkokkelk/eu.rkokkelk.xboxone). 

Big thanks for your work in the README.

**Comment by WeeJeWel** [comment]
Hi Roy!

Changing the app's id will break many things, such as auto-updates and installed devices. I really recommend you to keep it what it was :)

**Comment by rkokkelk** [comment]
Ah, that explains the update issues. Well then I'll reverse it again, no problem! Will also rename the repo to your original ID.
